#!/usr/bin/env bash
# Installs conda and sets the necessary configuration

# Create miniconda directory
mkdir -p ~/.miniconda
mkdir -p ~/tmp

# Download miniconda installer
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/tmp/miniconda.sh

# Verify installer's data integrity using SHA-256
shasum -a 256 ~/tmp/miniconda.sh

# Install miniconda and clean up
bash ~/tmp/miniconda.sh -b -u -p ~/.miniconda
rm -rf ~/tmp/miniconda.sh

# Initialize miniconda
~/.miniconda/bin/conda init bash
source ~/.bashrc

# Toggle base environment is default activation behaviour
# conda config --set auto_activate_base True
#conda config --set auto_activate_base False

