#!/usr/bin/env bash
# Installs and creates an SSL Certificate using certbot

# Check if running as root user
if [[ $EUID -ne 0 ]]; then
    echo 'Please run this script as root or sudo'
    exit 1
fi

# Install Certbot
echo "Installing Certbot..."
apt-get update
apt-get install -y certbot python3-certbot-nginx

# Check command-line arguments
if [ $# -ne 2 ]; then
    SCRIPT_NAME=$(basename "$0")
    echo "Usage: ./$SCRIPT_NAME YOUR_DOMAIN YOUR_EMAIL"
    echo "eg: ./$SCRIPT_NAME sub.example.com youremail@email.com"
    exit 1
fi

DOMAIN="$1"
EMAIL="$2"

# Obtain the SSL certificate
echo "Obtaining SSL certificate for $DOMAIN..."
certbot certonly --nginx --agree-tos --no-eff-email --email "$EMAIL" -d "$DOMAIN"

# Check if the certificate is successfully obtained
if [ $? -eq 0 ]; then
    echo "SSL certificate for $DOMAIN obtained successfully."
    # Create PEM file
    CERT_PATH="/etc/letsencrypt/live/$DOMAIN"
    PEM_PATH="/etc/ssl/$DOMAIN/$DOMAIN.pem"
    
    if [ -f "$CERT_PATH/fullchain.pem" ] && [ -f "$CERT_PATH/privkey.pem" ]; then
        mkdir -p "/etc/ssl/$DOMAIN"
        cat "$CERT_PATH/fullchain.pem" "$CERT_PATH/privkey.pem" > "$PEM_PATH"
        echo "SSL certificate created and configured for $DOMAIN."
    else
        echo "Error: Fullchain or privkey not found. Certificate might not have been generated successfully."
    fi
else
    echo "Failed to obtain SSL certificate for $DOMAIN."
    exit 1
fi

# Restart Nginx to apply the changes
systemctl restart nginx
