#!/usr/bin/env bash
#
# Author: Paul John
#
# Script to enable and disable sites (web server configuration)
# The script is for Nginx web server configuration
#+with the path of configuration being /etc/nginx/conf.d
#+this is intended for enabling and disabling sites without
#+using the popular sites-enabled and sites-disabled method.
#
# I recommend you rename your configuration files in relation to
#+your web domain name.
#+Eg. for a domain example.com, the configuration file name should be
#+named as example.com.conf in the Nginx's configuration directory, conf.d

# check if running as root user (sudo)
if [[ $EUID -ne 0 ]]; then
    echo "Please run this script as root or sudo"
    exit 1
fi

CONF_FILE_PATH="/etc/nginx/conf.d"

# List available site configuration files
if [ $1 = "list" ]; then
    echo "Available site configuration files..."
    echo ""
    ls -1 "$CONF_FILE_PATH"
    exit 1
fi

# check command-line arguments
if [ $# -ne 2 ]; then
    SCRIPT_NAME=$(basename "$0")
    echo "Usage: ./$SCRIPT_NAME CONF_OPTION [ CONF_SITE_NAME ]"
    echo ""
    echo "To list available site confifuration files..."
    echo "sudo ./$SCRIPT_NAME list"
    echo ""
    echo "To enable a site run the command below..."
    echo "sudo ./$SCRIPT_NAME enable example.com"
    echo ""
    echo "To disable a site, run the command below..."
    echo "sudo ./$SCRIPT_NAME disable example.com"

    exit 1
fi

CONF_OPTION="$1"
CONF_SITE_NAME="$2"


if [ -f "$CONF_FILE_PATH/$CONF_SITE_NAME.conf" ] && [ "$1" = "disable" ]; then
    echo "Disabling site..."
    mv "$CONF_FILE_PATH/$CONF_SITE_NAME.conf" "$CONF_FILE_PATH/$CONF_SITE_NAME.conf.disabled"
else 
    if [ -f "$CONF_FILE_PATH/$CONF_SITE_NAME.conf.disabled" ] && [ "$1" = "enable" ]; then
        echo "Enabling site..."
        mv "$CONF_FILE_PATH/$CONF_SITE_NAME.conf.disabled" "$CONF_FILE_PATH/$CONF_SITE_NAME.conf"
    else
        echo "Invalid option or site name not available!"
        echo ""
        echo "site names should only be the first part of the site configuration name before the .conf* part."
        echo "Eg. For configuration file 'example.com.conf' site name becomes 'example.com'"
        echo ""
        echo "Available sites names..."
        ls "$CONF_FILE_PATH"
        exit 1
    fi
fi

# Restart nginx web server
service nginx restart
echo "success..."
