#!/usr/bin/env bash
# Generates an SSH key and authorized_keys file

# Check command-line arguments
if [ "$#" -ne 2 ]; then
    SCRIPT_NAME=$(basename "$0")
    echo "Usage: ./$SCRIPT_NAME KEY_NAME COMMENT"
    echo "eg: ./$SCRIPT_NAME my_key youremail@gmail.com"
    exit 1
fi

# Generate SSH key
KEY_NAME="$1"
COMMENT="$2"

ssh-keygen -t rsa -b 4096 -f "$KEY_NAME" -C "$COMMENT"

# Copy the public key to authorized_keys file
mkdir -p ~/.ssh
cp "$KEY_NAME.pub" authorized_keys

echo "SSH key generated successfully!"
